### ISSUE TITLE
/usr/include/xqc.h conflicts with libxqilla-dev

### ISSUE THREAD

**Issue by darked89** [28msec/zorba#194]
Hello,

while installing zorba 3.0 using Synapse (Lubuntu 15.04),  I got the error:

E: /var/cache/apt/archives/zorba_3.1.0-0~ubuntu15.04.1_amd64.deb: trying to overwrite '/usr/include/xqc.h', which is also in package libxqilla-dev 2.3.0-2

Before this I did:
sudo add-apt-repository ppa:fcavalieri/zorba
sudo apt-get update

Well, I can remove libxqilla-dev and reinstall xqilla  i.e. in /usr/local but this is not the optimal solution. Some other program depends on xqilla.

Any simple ways of fixing this? Brain dead  rename of /usr/include/xqc.h to /usr/include/xqc.h.libxqilla-dev still does not let me install zorba in Synapse (info about package-specific provided files did not change  -> correct behavior).

Many thanks for your help,

Darek Kedra

**Comment by fcavalieri** [comment]
Hello Darek,

I believe you almost certainly don't need the /usr/include/xqc.h file.

It's the public header file for the semi-standard XQC C-binding for XQuery,
which is not really a completed project. Unless you specifically know you
need XQC, xqc.h is irrelevant.

(FYI, In an old message Chris Hillery wrote that in theory the file should
be the same between Zorba and XQilla, as the two teams collaborated on the
definition of the API and the contents of that header file. But it's been a
few years since anything was done there, so I'm not totally surprised they
drifted apart.)

I think the debian way to avoid the issue would be to use dpkg-divert (
http://linux.die.net/man/8/dpkg-divert). I didn't test it, but something
like this should work:

dpkg-divert --local --divert /usr/include/xqc.h.zorba --rename
/usr/include/xqc.h

Alternatively you can modify the source, remove the following line from
include/CMakeLists.txt in the Zorba project:

INSTALL(FILES xqc.h DESTINATION include)

Kind regards,
Federico

**Comment by darked89** [comment]
Hello Federico ,

thanks for the prompt answer. Here is the tested recipe: 
1. I installed config-package-dev using Synapse to get dpkg-divert
2. run
`sudo dpkg-divert --package zorba  --divert /usr/include/xqc.h.libxqilla --rename /usr/include/xqc.h`
3. installed zorba (+ zorba-csv-module and zorba-data-cleaning-module) using Synapse
4. checking the zorba version:
`zorba -v`
 `Zorba NoSQL Query Processor, Version: 3.1.0`

Thanks again,

Darek Kedra
